In [ ]:
import pandas as pd
import numpy as np

In [ ]:
gam = "/content/drive/MyDrive/drive-download-20260210T164924Z-1-001/games.csv/games.csv"
games = pd.read_csv(gam)
games.head(5)

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,22-12-2022,22200477,Final,1610612740,1610612759,2022,1610612740,126.0,0.484,0.926,...,25.0,46.0,1610612759,117.0,0.478,0.815,0.321,23.0,44.0,1
1,22-12-2022,22200478,Final,1610612762,1610612764,2022,1610612762,120.0,0.488,0.952,...,16.0,40.0,1610612764,112.0,0.561,0.765,0.333,20.0,37.0,1
2,21-12-2022,22200466,Final,1610612739,1610612749,2022,1610612739,114.0,0.482,0.786,...,22.0,37.0,1610612749,106.0,0.470,0.682,0.433,20.0,46.0,1
3,21-12-2022,22200467,Final,1610612755,1610612765,2022,1610612755,113.0,0.441,0.909,...,27.0,49.0,1610612765,93.0,0.392,0.735,0.261,15.0,46.0,1
4,21-12-2022,22200468,Final,1610612737,1610612741,2022,1610612737,108.0,0.429,1.000,...,22.0,47.0,1610612741,110.0,0.500,0.773,0.292,20.0,47.0,0

In [ ]:
rank = "/content/drive/MyDrive/drive-download-20260210T164924Z-1-001/ranking.csv/ranking.csv"
ranking = pd.read_csv(rank)
ranking = ranking.drop
ranking.head(5)

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612743,0,22022,22-12-2022,West,Denver,30,19,11,0.633,10-Mar,09-Aug,NaN
1,1610612763,0,22022,22-12-2022,West,Memphis,30,19,11,0.633,13-Feb,06-Sep,NaN
2,1610612740,0,22022,22-12-2022,West,New Orleans,31,19,12,0.613,13-Apr,06-Aug,NaN
3,1610612756,0,22022,22-12-2022,West,Phoenix,32,19,13,0.594,14-Apr,05-Sep,NaN
4,1610612746,0,22022,22-12-2022,West,LA Clippers,33,19,14,0.576,11-Jul,08-Jul,NaN

In [ ]:
gamls = "/content/drive/MyDrive/drive-download-20260210T164924Z-1-001/games_details.csv/games_details.csv"
game_details = pd.read_csv(gamls, dtype={'PLAYER_NAME': str}, low_memory=False)
game_details.head(5)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01:00,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20:00,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44:00,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0

In [ ]:
play = "/content/drive/MyDrive/drive-download-20260210T164924Z-1-001/players.csv"
players = pd.read_csv(play)
players.head(5)

        PLAYER_NAME     TEAM_ID  PLAYER_ID  SEASON
0     Royce O'Neale  1610612762    1626220    2019
1  Bojan Bogdanovic  1610612762     202711    2019
2       Rudy Gobert  1610612762     203497    2019
3  Donovan Mitchell  1610612762    1628378    2019
4       Mike Conley  1610612762     201144    2019

In [ ]:
team = "/content/drive/MyDrive/drive-download-20260210T164924Z-1-001/teams.csv"
teams = pd.read_csv(team)
teams.head(5)

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Lloyd Pierce,Erie Bayhawks
1,0,1610612738,1946,2019,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate
3,0,1610612741,1966,2019,CHI,Bulls,1966,Chicago,United Center,21711.0,Jerry Reinsdorf,Gar Forman,Jim Boylen,Windy City Bulls
4,0,1610612742,1980,2019,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Mark Cuban,Donnie Nelson,Rick Carlisle,Texas Legends

In [ ]:
games.info()
game_details.info()
ranking.info()
players.info()
teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26651 entries, 0 to 26650
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     26651 non-null  object
 1   GAME_ID           26651 non-null  int64
 2   GAME_STATUS_TEXT  26651 non-null  object
 3   HOME_TEAM_ID      26651 non-null  int64
 4   VISITOR_TEAM_ID   26651 non-null  int64
 5   SEASON            26651 non-null  int64
 6   TEAM_ID_home      26651 non-null  int64
 7   PTS_home          26552 non-null  float64
 8   FG_PCT_home       26552 non-null  float64
 9   FT_PCT_home       26552 non-null  float64
 10  FG3_PCT_home      26552 non-null  float64
 11  AST_home          26552 non-null  float64
 12  REB_home          26552 non-null  float64
 13  TEAM_ID_away      26651 non-null  int64
 14  PTS_away          26552 non-null  float64
 15  FG_PCT_away       26552 non-null  float64
 16  FT_PCT_away       26552 non-null  float64
 17  FG3_PCT_away      26552 non-null  float64
 18  AST_away          26552 non-null  float64
 19  REB_away          26552 non-null  float64
 20  HOME_TEAM_WINS    26651 non-null  int64
dtypes: float64(12), int64(7), object(2)
memory usage: 4.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668628 entries, 0 to 668627
Data columns (total 29 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   GAME_ID            668628 non-null  int64
 1   TEAM_ID            668628 non-null  int64
 2   TEAM_ABBREVIATION  668628 non-null  object
 3   TEAM_CITY          668628 non-null  object
 4   PLAYER_ID          668628 non-null  int64
 5   PLAYER_NAME        668628 non-null  object
 6   NICKNAME           53037 non-null   object
 7   START_POSITION     255765 non-null  object
 8   COMMENT            109689 non-null  object
 9   MIN                558938 non-null  object
 10  FGM                558938 non-null  float64
 11  FGA                558938 non-null  float64
 12  FG_PCT             558938 non-null  float64
 13  FG3M               558938 non-null  float64
 14  FG3A               558938 non-null  float64
 15  FG3_PCT            558938 non-null  float64
 16  FTM                558938 non-null  float64
 17  FTA                558938 non-null  float64
 18  FT_PCT             558938 non-null  float64
 19  OREB               558938 non-null  float64
 20  DREB               558938 non-null  float64
 21  REB                558938 non-null  float64
 22  AST                558938 non-null  float64
 23  STL                558938 non-null  float64
 24  BLK                558938 non-null  float64
 25  TO                 558938 non-null  float64
 26  PF                 558938 non-null  float64
 27  PTS                558938 non-null  float64
 28  PLUS_MINUS         535277 non-null  float64
dtypes: float64(19), int64(3), object(7)
memory usage: 147.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210342 entries, 0 to 210341
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TEAM_ID        210342 non-null  int64
 1   LEAGUE_ID      210342 non-null  int64
 2   SEASON_ID      210342 non-null  int64
 3   STANDINGSDATE  210342 non-null  object
 4   CONFERENCE     210342 non-null  object
 5   TEAM           210342 non-null  object
 6   G              210342 non-null  int64
 7   W              210342 non-null  int64
 8   L              210342 non-null  int64
 9   W_PCT          210342 non-null  float64
 10  HOME_RECORD    210342 non-null  object
 11  ROAD_RECORD    210342 non-null  object
 12  RETURNTOPLAY   3990 non-null    float64
dtypes: float64(2), int64(6), object(5)
memory usage: 20.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7228 entries, 0 to 7227
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PLAYER_NAME  7228 non-null   object
 1   TEAM_ID      7228 non-null   int64
 2   PLAYER_ID    7228 non-null   int64
 3   SEASON       7228 non-null   int64
dtypes: int64(3), object(1)
memory usage: 226.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   LEAGUE_ID           30 non-null     int64
 1   TEAM_ID             30 non-null     int64
 2   MIN_YEAR            30 non-null     int64
 3   MAX_YEAR            30 non-null     int64
 4   ABBREVIATION        30 non-null     object
 5   NICKNAME            30 non-null     object
 6   YEARFOUNDED         30 non-null     int64
 7   CITY                30 non-null     object
 8   ARENA               30 non-null     object
 9   ARENACAPACITY       26 non-null     float64
 10  OWNER               30 non-null     object
 11  GENERALMANAGER      30 non-null     object
 12  HEADCOACH           30 non-null     object
 13  DLEAGUEAFFILIATION  30 non-null     object
dtypes: float64(1), int64(5), object(8)
memory usage: 3.4+ KB

In [ ]:
games.isnull().sum()

GAME_DATE_EST        0
GAME_ID              0
GAME_STATUS_TEXT     0
HOME_TEAM_ID         0
VISITOR_TEAM_ID      0
SEASON               0
TEAM_ID_home         0
PTS_home            99
FG_PCT_home         99
FT_PCT_home         99
FG3_PCT_home        99
AST_home            99
REB_home            99
TEAM_ID_away         0
PTS_away            99
FG_PCT_away         99
FT_PCT_away         99
FG3_PCT_away        99
AST_away            99
REB_away            99
HOME_TEAM_WINS       0
dtype: int64

In [ ]:
games = games.dropna()

As null value rows are only 99 which are much smaller than original dataset, so we dropped them.

In [ ]:
games.isnull().sum()

GAME_DATE_EST       0
GAME_ID             0
GAME_STATUS_TEXT    0
HOME_TEAM_ID        0
VISITOR_TEAM_ID     0
SEASON              0
TEAM_ID_home        0
PTS_home            0
FG_PCT_home         0
FT_PCT_home         0
FG3_PCT_home        0
AST_home            0
REB_home            0
TEAM_ID_away        0
PTS_away            0
FG_PCT_away         0
FT_PCT_away         0
FG3_PCT_away        0
AST_away            0
REB_away            0
HOME_TEAM_WINS      0
dtype: int64

In [ ]:
game_details.isnull().sum()

GAME_ID                   0
TEAM_ID                   0
TEAM_ABBREVIATION         0
TEAM_CITY                 0
PLAYER_ID                 0
PLAYER_NAME               0
NICKNAME             615591
START_POSITION       412863
COMMENT              558939
MIN                  109690
FGM                  109690
FGA                  109690
FG_PCT               109690
FG3M                 109690
FG3A                 109690
FG3_PCT              109690
FTM                  109690
FTA                  109690
FT_PCT               109690
OREB                 109690
DREB                 109690
REB                  109690
AST                  109690
STL                  109690
BLK                  109690
TO                   109690
PF                   109690
PTS                  109690
PLUS_MINUS           133351
dtype: int64

In [ ]:
cols = ['MIN','FGM','FGA','FG_PCT','FG3M','FG3A','FG3_PCT',
        'FTM','FTA','FT_PCT','OREB','DREB','REB','AST',
        'STL','BLK','TO','PF','PTS','PLUS_MINUS']

game_details[cols] = game_details[cols].fillna(0)

In [ ]:
game_details = game_details.drop(columns=['NICKNAME','COMMENT'], errors='ignore')

In [ ]:
games['GAME_DATE_EST'] = pd.to_datetime(games['GAME_DATE_EST'], dayfirst=True)

In [ ]:
game_details['START_POSITION'] = game_details['START_POSITION'].fillna('Bench')

In [ ]:
game_details.isnull().sum()

GAME_ID              0
TEAM_ID              0
TEAM_ABBREVIATION    0
TEAM_CITY            0
PLAYER_ID            0
PLAYER_NAME          0
START_POSITION       0
MIN                  0
FGM                  0
FGA                  0
FG_PCT               0
FG3M                 0
FG3A                 0
FG3_PCT              0
FTM                  0
FTA                  0
FT_PCT               0
OREB                 0
DREB                 0
REB                  0
AST                  0
STL                  0
BLK                  0
TO                   0
PF                   0
PTS                  0
PLUS_MINUS           0
dtype: int64

In [ ]:
game_details.drop_duplicates(inplace=True)

In [ ]:
ranking.isnull().sum()

TEAM_ID               0
LEAGUE_ID             0
SEASON_ID             0
STANDINGSDATE         0
CONFERENCE            0
TEAM                  0
G                     0
W                     0
L                     0
W_PCT                 0
HOME_RECORD           0
ROAD_RECORD           0
RETURNTOPLAY     206352
dtype: int64

In [ ]:
ranking.drop_duplicates(inplace=True)

In [ ]:
ranking['RETURNTOPLAY'] = ranking['RETURNTOPLAY'].fillna('Not Applicable')

In [ ]:
teams.isnull().sum()

LEAGUE_ID             0
TEAM_ID               0
MIN_YEAR              0
MAX_YEAR              0
ABBREVIATION          0
NICKNAME              0
YEARFOUNDED           0
CITY                  0
ARENA                 0
ARENACAPACITY         4
OWNER                 0
GENERALMANAGER        0
HEADCOACH             0
DLEAGUEAFFILIATION    0
dtype: int64

In [ ]:
# =========================
# 1. GAMES TABLE
# =========================
games = games.drop(columns=[
    'GAME_STATUS_TEXT'
], errors='ignore')


# =========================
# 2. GAME_DETAILS TABLE
# =========================
game_details = game_details.drop(columns=[
    'NICKNAME',
    'COMMENT',
    'TEAM_ABBREVIATION',
    'TEAM_CITY',
    'START_POSITION',
    'MIN','FGM','FGA','FG_PCT',
    'FG3M','FG3A','FG3_PCT',
    'FTM','FTA','FT_PCT',
    'OREB','DREB','PF'
], errors='ignore')

# Keep only required columns (FINAL OPTIMIZATION)
game_details = game_details[
    ['GAME_ID','PLAYER_ID','TEAM_ID',
     'PTS','AST','REB','STL','BLK','TO','PLUS_MINUS']
]


# =========================
# 3. RANKINGS TABLE
# =========================
ranking = ranking.drop(columns=[
    'RETURNTOPLAY',
    'LEAGUE_ID', 'HOME_RECORD', 'ROAD_RECORD' ], errors='ignore')


# =========================
# 4. TEAMS TABLE
# =========================
teams = teams.drop(columns=[
    'LEAGUE_ID','MIN_YEAR','MAX_YEAR',
    'ARENA','ARENACAPACITY',
    'OWNER','GENERALMANAGER',
    'HEADCOACH','DLEAGUEAFFILIATION'
], errors='ignore')

# Keep only useful columns
teams = teams[
    ['TEAM_ID','CITY','NICKNAME','YEARFOUNDED']
]


# =========================
# 5. PLAYERS TABLE
# =========================
players = players[['PLAYER_ID','PLAYER_NAME','SEASON']]


# =========================
# FINAL CHECK
# =========================
print("Games:", games.shape)
print("Game Details:", game_details.shape)
print("Ranking:", ranking.shape)
print("Teams:", teams.shape)
print("Players:", players.shape)

Games: (26552, 26)
Game Details: (668345, 10)
Ranking: (210313, 17)
Teams: (30, 4)
Players: (7228, 3)

In [ ]:
games['TOTAL_POINTS'] = games['PTS_home'] + games['PTS_away']

In [ ]:
games['POINT_DIFF'] = abs(games['PTS_home'] - games['PTS_away'])

In [ ]:
games['WINNER_TEAM_ID'] = np.where(
    games['HOME_TEAM_WINS'] == 1,
    games['TEAM_ID_home'],
    games['TEAM_ID_away']
)

In [ ]:
games['YEAR'] = games['GAME_DATE_EST'].dt.year

In [ ]:
game_details['EFFICIENCY'] = (
    game_details['PTS'] +
    game_details['REB'] +
    game_details['AST'] +
    game_details['STL'] +
    game_details['BLK'] -
    game_details['TO']
)

In [ ]:
game_details['IMPACT'] = game_details['PTS'] + game_details['PLUS_MINUS']

In [ ]:
game_details['OFFENSE'] = game_details['PTS'] + game_details['AST']

In [ ]:
ranking['WIN_RATIO'] = ranking['W'] / (ranking['W'] + ranking['L'])

In [ ]:
games['CLOSE_GAME'] = games['POINT_DIFF'] <= 5

In [ ]:
games['HIGH_SCORING'] = games['TOTAL_POINTS'] > 220

In [ ]:
ranking['STANDINGSDATE'] = pd.to_datetime(
    ranking['STANDINGSDATE'],
    dayfirst=True,
    errors='coerce'
)

In [ ]:
ranking['YEAR'] = ranking['STANDINGSDATE'].dt.year

In [ ]:
games.to_csv("final_games.csv", index=False)
game_details.to_csv("final_game_details.csv", index=False)
ranking.to_csv("final_rankings.csv", index=False)
teams.to_csv("final_teams.csv", index=False)
players.to_csv("final_players.csv", index=False)

In [ ]:
Home_stats = games.groupby(['SEASON','TEAM_ID_home']).agg(
    TOTAL_HOME_GAMES=('GAME_ID','count'),
    AVG_HOME_POINTS=('PTS_home','mean'),
    TOTAL_HOME_WINS=('HOME_TEAM_WINS','sum')
).reset_index()

In [ ]:
Away_stats = games.groupby(['SEASON','TEAM_ID_away']).agg(
    TOTAL_AWAY_GAMES=('GAME_ID','count'),
    AVG_AWAY_POINTS=('PTS_away','mean'),
    TOTAL_AWAY_WINS=('HOME_TEAM_WINS', lambda x: (1 - x).sum())
).reset_index()

In [ ]:
team_summary = pd.merge(
    Home_stats,
    Away_stats,
    left_on=['SEASON','TEAM_ID_home'],
    right_on=['SEASON','TEAM_ID_away'],
    how='outer'
)

In [ ]:
team_summary['TEAM_ID'] = team_summary['TEAM_ID_home'].combine_first(team_summary['TEAM_ID_away'])

team_summary['TOTAL_GAMES'] = team_summary['TOTAL_HOME_GAMES'].fillna(0) + team_summary['TOTAL_AWAY_GAMES'].fillna(0)

team_summary['TOTAL_WINS'] = team_summary['TOTAL_HOME_WINS'].fillna(0) + team_summary['TOTAL_AWAY_WINS'].fillna(0)

team_summary['WIN_PCT'] = team_summary['TOTAL_WINS'] / team_summary['TOTAL_GAMES']

team_summary['AVG_POINTS'] = (
    team_summary['AVG_HOME_POINTS'].fillna(0) +
    team_summary['AVG_AWAY_POINTS'].fillna(0)
) / 2

In [ ]:
# =========================
# STEP 1: BASE AGGREGATION
# =========================
player_summary = game_details.groupby(['PLAYER_ID']).agg(
    AVG_POINTS=('PTS','mean'),
    AVG_AST=('AST','mean'),
    AVG_REB=('REB','mean'),
    AVG_EFFICIENCY=('EFFICIENCY','mean'),
    TOTAL_GAMES=('GAME_ID','count')
).reset_index()


# =========================
# STEP 2: CONSISTENCY (STD)
# =========================
player_std = game_details.groupby('PLAYER_ID')['PTS'].std().reset_index()
player_std.rename(columns={'PTS':'POINTS_STD'}, inplace=True)

player_summary = pd.merge(
    player_summary,
    player_std,
    on='PLAYER_ID',
    how='left'
)


# =========================
# STEP 3: CLEAN PLAYERS TABLE
# =========================
players_unique = players[['PLAYER_ID','PLAYER_NAME']].drop_duplicates()


# =========================
# STEP 4: REMOVE OLD NAME COLS (AVOID ERRORS)
# =========================
player_summary = player_summary.drop(columns=[
    'PLAYER_NAME','PLAYER_NAME_x','PLAYER_NAME_y'
], errors='ignore')


# =========================
# STEP 5: MERGE PLAYER NAMES
# =========================
player_summary = pd.merge(
    player_summary,
    players_unique,
    on='PLAYER_ID',
    how='left'
)


# =========================
# STEP 6: FILTER IMPORTANT PLAYERS
# =========================
player_summary = player_summary[player_summary['TOTAL_GAMES'] > 20]


# =========================
# STEP 7: CREATE PLAYER CATEGORY
# =========================
player_summary['PLAYER_LEVEL'] = pd.cut(
    player_summary['AVG_POINTS'],
    bins=[0,10,20,30,100],
    labels=['Low','Average','Good','Elite']
)


# =========================
# STEP 8: SORT FOR DASHBOARD
# =========================
player_summary = player_summary.sort_values(
    by='AVG_POINTS',
    ascending=False
)


# =========================
# STEP 9: FINAL CHECK
# =========================
print(player_summary.head())

print("Unique Players:", player_summary['PLAYER_ID'].nunique())
print("Total Rows:", len(player_summary))


# =========================
# STEP 10: SAVE FILE
# =========================
player_summary.to_csv("player_summary.csv", index=False)

      PLAYER_ID  AVG_POINTS   AVG_AST   AVG_REB  AVG_EFFICIENCY  TOTAL_GAMES  \
876      201142   26.495895  4.130542  6.885057       36.594417         1218
2106    1629029   26.244253  7.675287  8.250000       39.781609          348
465        2544   25.982163  6.947603  7.325530       39.159420         1794
141         977   24.761343  4.574410  4.915608       33.064428         1102
2104    1629027   24.214286  8.659341  3.576923       33.519231          364

      POINTS_STD   PLAYER_NAME PLAYER_LEVEL
876     8.840153  Kevin Durant         Good
2106    9.418579   Luka Doncic         Good
465     9.342508  LeBron James         Good
141    11.959523   Kobe Bryant         Good
2104   10.756417    Trae Young         Good
Unique Players: 1869
Total Rows: 1869

In [ ]:
game_summary = games.groupby('SEASON').agg(
    AVG_POINTS=('TOTAL_POINTS','mean'),
    TOTAL_GAMES=('GAME_ID','count')
).reset_index()

In [ ]:
team_summary.to_csv("team_summary.csv", index=False)
player_summary.to_csv("player_summary.csv", index=False)
game_summary.to_csv("game_summary.csv", index=False)

In [ ]:
from google.colab import files

In [ ]:

files.download("final_rankings.csv")
files.download("team_summary.csv")
files.download("player_summary.csv")
files.download("game_summary.csv")
files.download("final_teams.csv")

In [ ]:
files.download("final_games.csv")

In [ ]:
files.download("final_rankings.csv")